apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: databaseuser-editor-role-binding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: staffbase-operator
    app.kubernetes.io/part-of: staffbase-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseuser-editor-role-binding
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
roleRef:
  kind: ClusterRole
  name: databaseuser-editor-role
  apiGroup: rbac.authorization.k8s.io
